name: joinmassage
version: '${project.version}'
main: org.uminokun.joinmassage.Joinmassage
api-version: '1.20'
commands:
  test:
    description: This is a demo command.
    usage: /<command>
    permission: joinmassage.command
    permission-message: You don't have <permission>